"""empty message

Revision ID: ab662e724d7d
Revises: 81d9c23bfbc4
Create Date: 2025-12-03 11:29:17.419140+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab662e724d7d"
down_revision: str | Sequence[str] | None = "81d9c23bfbc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.alter_column(
            "update_ts",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default="(CURRENT_TIMESTAMP)",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.alter_column(
            "update_ts",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default="(CURRENT_TIMESTAMP)",
        )

    # ### end Alembic commands ###
