"""empty message

Revision ID: 19736cab8aa5
Revises: 47ed5b57007a
Create Date: 2025-12-06 15:15:45.020323+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19736cab8aa5"
down_revision: str | Sequence[str] | None = "47ed5b57007a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distributionpackagelink",
        sa.Column("distribution_id", sa.Integer(), nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["distribution_id"], ["distribution.id"]),
        sa.ForeignKeyConstraint(["package_id"], ["package.id"]),
        sa.PrimaryKeyConstraint("distribution_id", "package_id"),
    )
    with op.batch_alter_table("distributionpackagelink", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dist_pkg_distribution_package", ["distribution_id", "package_id"], unique=False
        )

    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_fetched_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.drop_column("update_ts")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "update_ts",
                sa.DATETIME(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.drop_column("last_fetched_at")

    with op.batch_alter_table("distributionpackagelink", schema=None) as batch_op:
        batch_op.drop_index("ix_dist_pkg_distribution_package")

    op.drop_table("distributionpackagelink")
    # ### end Alembic commands ###
