"""
Message: empty message

Revision ID: 47ed5b57007a
Revises:
Create Date: 2025-12-06 14:26:25.498731+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel as sm
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47ed5b57007a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sm.AutoString(), nullable=False),
        sa.Column("url", sm.AutoString(), nullable=False),
        sa.Column(
            "update_ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_repository_name"), ["name"], unique=True)
        batch_op.create_index(batch_op.f("ix_repository_url"), ["url"], unique=True)

    op.create_table(
        "architecture",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sm.AutoString(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repository.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "name", name="uq_architecture_distribution_name"),
    )
    with op.batch_alter_table("architecture", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_architecture_name"), ["name"], unique=True)

    op.create_table(
        "component",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sm.AutoString(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repository.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "name", name="uq_component_distribution_name"),
    )
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_component_name"), ["name"], unique=True)

    op.create_table(
        "distribution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sm.AutoString(), nullable=False),
        sa.Column("date", sm.AutoString(), nullable=True),
        sa.Column("description", sm.AutoString(), nullable=True),
        sa.Column("origin", sm.AutoString(), nullable=True),
        sa.Column("suite", sm.AutoString(), nullable=True),
        sa.Column("version", sm.AutoString(), nullable=True),
        sa.Column("codename", sm.AutoString(), nullable=True),
        sa.Column("architecture_names", sa.JSON(), nullable=False),
        sa.Column("component_names", sa.JSON(), nullable=False),
        sa.Column("raw", sm.AutoString(), nullable=True),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column(
            "last_fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repository.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "name", name="uq_distribution_repository_name"),
    )
    with op.batch_alter_table("distribution", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_distribution_name"), ["name"], unique=False)

    op.create_table(
        "distributionarchitecturelink",
        sa.Column("architecture_id", sa.Integer(), nullable=False),
        sa.Column("distribution_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["architecture_id"], ["architecture.id"]),
        sa.ForeignKeyConstraint(["distribution_id"], ["distribution.id"]),
        sa.PrimaryKeyConstraint("architecture_id", "distribution_id"),
    )
    with op.batch_alter_table("distributionarchitecturelink", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dist_arch_distribution_architecture", ["distribution_id", "architecture_id"], unique=False
        )

    op.create_table(
        "distributioncomponentlink",
        sa.Column("component_id", sa.Integer(), nullable=False),
        sa.Column("distribution_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["component.id"],
        ),
        sa.ForeignKeyConstraint(
            ["distribution_id"],
            ["distribution.id"],
        ),
        sa.PrimaryKeyConstraint("component_id", "distribution_id"),
    )
    with op.batch_alter_table("distributioncomponentlink", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dist_comp_distribution_component", ["distribution_id", "component_id"], unique=False
        )

    op.create_table(
        "package",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sm.AutoString(), nullable=False),
        sa.Column("version", sm.AutoString(), nullable=False),
        sa.Column("section", sm.AutoString(), nullable=True),
        sa.Column("priority", sm.AutoString(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("installed_size", sa.BigInteger(), nullable=True),
        sa.Column("filename", sm.AutoString(), nullable=True),
        sa.Column("source", sm.AutoString(), nullable=True),
        sa.Column("maintainer", sm.AutoString(), nullable=True),
        sa.Column("homepage", sm.AutoString(), nullable=True),
        sa.Column("description", sm.AutoString(), nullable=True),
        sa.Column("description_md5", sm.AutoString(), nullable=True),
        sa.Column("checksum_md5", sm.AutoString(), nullable=True),
        sa.Column("checksum_sha1", sm.AutoString(), nullable=True),
        sa.Column("checksum_sha256", sm.AutoString(), nullable=True),
        sa.Column("tags", sm.AutoString(), nullable=True),
        sa.Column("raw_control", sa.JSON(), nullable=True),
        sa.Column("distribution_id", sa.Integer(), nullable=False),
        sa.Column("component_id", sa.Integer(), nullable=False),
        sa.Column("architecture_id", sa.Integer(), nullable=False),
        sa.Column(
            "last_fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["architecture_id"], ["architecture.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["component_id"], ["component.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["distribution_id"], ["distribution.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "distribution_id",
            "component_id",
            "architecture_id",
            "name",
            "version",
            name="uq_package_distribution_component_architecture_name_version",
        ),
    )
    with op.batch_alter_table("package", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_package_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_package_version"), ["version"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("package", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_package_version"))
        batch_op.drop_index(batch_op.f("ix_package_name"))

    op.drop_table("package")
    with op.batch_alter_table("distributioncomponentlink", schema=None) as batch_op:
        batch_op.drop_index("ix_dist_comp_distribution_component")

    op.drop_table("distributioncomponentlink")
    with op.batch_alter_table("distributionarchitecturelink", schema=None) as batch_op:
        batch_op.drop_index("ix_dist_arch_distribution_architecture")

    op.drop_table("distributionarchitecturelink")
    with op.batch_alter_table("distribution", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_distribution_name"))

    op.drop_table("distribution")
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_component_name"))

    op.drop_table("component")
    with op.batch_alter_table("architecture", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_architecture_name"))

    op.drop_table("architecture")
    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repository_url"))
        batch_op.drop_index(batch_op.f("ix_repository_name"))

    op.drop_table("repository")
    # ### end Alembic commands ###
