"""empty message

Revision ID: 4bb1ffbc00d3
Revises: 46b315a3dea5
Create Date: 2025-12-06 07:06:23.190038+00:00

"""

from typing import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bb1ffbc00d3"
down_revision: str | Sequence[str] | None = "46b315a3dea5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("package", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_name_version"), type_="unique")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("package", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_name_version"), ["name", "version"])
