"""initial

Revision ID: 81d9c23bfbc4
Revises:
Create Date: 2025-12-03 07:56:25.254867+00:00

"""

from typing import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81d9c23bfbc4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.AutoString(), nullable=False),
        sa.Column(
            "update_ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_repository_name"), ["name"], unique=True)
        batch_op.create_index(batch_op.f("ix_repository_url"), ["url"], unique=True)

    op.create_table(
        "distribution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw", sqlmodel.AutoString(), nullable=True),
        sa.Column("architectures", sa.JSON(), nullable=False),
        sa.Column("components", sa.JSON(), nullable=False),
        sa.Column("date", sqlmodel.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.AutoString(), nullable=True),
        sa.Column("origin", sqlmodel.AutoString(), nullable=False),
        sa.Column("suite", sqlmodel.AutoString(), nullable=False),
        sa.Column("version", sqlmodel.AutoString(), nullable=False),
        sa.Column("codename", sqlmodel.AutoString(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repository.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("distribution")
    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repository_url"))
        batch_op.drop_index(batch_op.f("ix_repository_name"))

    op.drop_table("repository")
    # ### end Alembic commands ###
