"""empty message

Revision ID: 539c3e6bfd23
Revises: fe8560280a24
Create Date: 2026-01-10 12:08:09.772876+00:00

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "539c3e6bfd23"
down_revision: str | Sequence[str] | None = "fe8560280a24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("package", schema=None) as batch_op:
        batch_op.create_index("ix_package_name_version", ["name", "version"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("package", schema=None) as batch_op:
        batch_op.drop_index("ix_package_name_version")

    # ### end Alembic commands ###
