"""let there be typed dates

Revision ID: bd1c1f7d71bb
Revises: 539c3e6bfd23
Create Date: 2026-01-12 10:30:35.044083+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bd1c1f7d71bb"
down_revision: str | Sequence[str] | None = "539c3e6bfd23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "distribution",
        "date",
        existing_type=sa.VARCHAR(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        postgresql_using="date::timestamptz",
    )
    op.create_index(op.f("ix_distribution_date"), "distribution", ["date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_distribution_date"), table_name="distribution")
    op.alter_column(
        "distribution",
        "date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        postgresql_using="date::varchar",
    )
    # ### end Alembic commands ###
