"""drop version-only index from package

Revision ID: 1f750c462c84
Revises: bd1c1f7d71bb
Create Date: 2026-01-15 09:42:59.103778+00:00

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1f750c462c84"
down_revision: str | Sequence[str] | None = "bd1c1f7d71bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_package_version"), table_name="package")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_package_version"), "package", ["version"], unique=False)
    # ### end Alembic commands ###
